
(defun sweyla852454 ()
  "Theme generated by Sweyla: http://sweyla.com/themes/seed/852454/"
  (interactive)
  (color-theme-install
   '(sweyla852454
     ((background-color . "#000200")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#6CFFC5"))))
     (font-lock-constant-face ((t (:foreground "#D4E5FF"))))
     (font-lock-builtin-face ((t (:foreground "#6EAAFF"))))
     (font-lock-function-name-face ((t (:foreground "#3A7BE4"))))
     (font-lock-variable-name-face ((t (:foreground "#6EFFDE"))))
     (font-lock-keyword-face ((t (:foreground "#B1F98F"))))
     (font-lock-string-face ((t (:foreground "#13D0F1"))))
     (font-lock-doc-string-face ((t (:foreground "#13D0F1"))))
     (font-lock-type-face ((t (:foreground "#B28EFF"))))
     )))

(provide 'sweyla852454)
